/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.wavemaker.testcharts203.sales.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
import com.wavemaker.testcharts203.sales.service.SalesDataService;
import java.io.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.hibernate.TypeMismatchException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.runtime.util.WMRuntimeUtils;
import com.wordnik.swagger.annotations.*;
import com.wavemaker.testcharts203.sales.*;
import com.wavemaker.testcharts203.sales.service.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

/**
 * Controller object for domain model class SalesData.
 * @see com.wavemaker.testcharts203.sales.SalesData
 */
@RestController(value = "Sales.SalesDataController")
@RequestMapping("/Sales/SalesData")
@Api(description = "Exposes APIs to work with SalesData resource.", value = "SalesDataController")
public class SalesDataController {

    private static final Logger LOGGER = LoggerFactory.getLogger(SalesDataController.class);

    @Autowired
    @Qualifier("Sales.SalesDataService")
    private SalesDataService salesDataService;

    /**
	 * This setter method should only be used by unit tests
	 * 
	 * @param service
	 */
    protected void setSalesDataService(SalesDataService service) {
        this.salesDataService = service;
    }

    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the list of SalesData instances matching the search criteria.")
    public Page<SalesData> findSalesDatas(Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering SalesDatas list");
        return salesDataService.findAll(queryFilters, pageable);
    }

    @RequestMapping(value = "/count", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the total count of SalesData instances.")
    public Long countAllSalesDatas() {
        LOGGER.debug("counting SalesDatas");
        Long count = salesDataService.countAll();
        return count;
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Deletes the SalesData instance associated with the given id.")
    public boolean deleteSalesData(@PathVariable(value = "id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting SalesData with id: {}", id);
        SalesData deleted = salesDataService.delete(id);
        return deleted != null;
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the SalesData instance associated with the given id.")
    public SalesData getSalesData(@PathVariable(value = "id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting SalesData with id: {}", id);
        SalesData instance = salesDataService.findById(id);
        LOGGER.debug("SalesData details with id: {}", instance);
        return instance;
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Updates the SalesData instance associated with the given id.")
    public SalesData editSalesData(@PathVariable(value = "id") Integer id, @RequestBody SalesData instance) throws EntityNotFoundException {
        LOGGER.debug("Editing SalesData with id: {}", instance.getId());
        instance.setId(id);
        instance = salesDataService.update(instance);
        LOGGER.debug("SalesData details with id: {}", instance);
        return instance;
    }

    @RequestMapping(value = "/", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Creates a new SalesData instance.")
    public SalesData createSalesData(@RequestBody SalesData instance) {
        LOGGER.debug("Create SalesData with information: {}", instance);
        instance = salesDataService.create(instance);
        LOGGER.debug("Created SalesData with information: {}", instance);
        return instance;
    }

    @RequestMapping(value = "/", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the list of SalesData instances.")
    public Page<SalesData> getSalesDatas(Pageable pageable) {
        LOGGER.debug("Rendering SalesDatas list");
        return salesDataService.findAll(pageable);
    }
}
